### PR TITLE
Fix irb_history saved to current directory

### LINKED ISSUE #674: Improve `.irbrc`'s loading behaviour
I noticed 2 "surprising" `.irbrc` loading behaviour recently:

### Lack of hierarchy on rc file loading

Unlike many other tools that have "project level" and "user level" configurations, IRB only accepts a single `.irbrc` file [through a fixed loading order](https://github.com/ruby/irb/blob/153b1e9d1cab945e4b21eba12c1654b5876e17e6/lib/irb/init.rb#L392-L411). 

For example, it doesn't load `project/.irbrc` if `~/.irbrc` is present.

This is unintuitive to most users as popular tools like `Pry` or `VS Code` both have "user level" and "project level" configurations. And they usually load "user level" configs first, and allow "project level" configs to override them.

```
$ pry        
~/.pryrc loaded
project/.pryrc loaded
[1] pry(main)> 
```

### `.irb_history` is always placed at the same place as `.irbrc` is defined

This is also not an intuitive design. Most of the time, `.irb_history` should not be inside the project folder. So the current reality is, if a project wants to define `.irbrc` for all its developers, `.irb_history` needs to be added to `.gitignore` or the project needs to configure `IRB.conf[:HISTORY_FILE]` ([example](https://github.com/Shopify/ruby-lsp/pull/858)).

### PR DESCRIPTION
**Pull request by tompng**
Fixes #674 with refactoring

IRB.rc_files is used for irbrc searching and irb_history searching. I think two separate logic is combined into one and making the code complicated.

### Changes
- Split `IRB.rc_files(ext)` to `IRB.irb_files` and `IRB.rc_file(ext)`
- history will be saved to `dirname(ENV['IRBRC'])`, `ENV['XDG_CONFIG_HOME']` or `ENV['HOME']`
- `IRB.conf[:RC_NAME_GENERATOR]` is removed because it's impossible to configure before loading irbrc
- Fix irbrc loaded twice bug mentioned in https://github.com/ruby/irb/issues/674#issuecomment-1994482350

### CODE REVIEW

File: test/irb/test_init.rb [hunk 1]
```diff
@@ -35,132 +40,82 @@ def test_setup_with_minimum_argv_does_not_change_dollar0
...
-      verbose, $VERBOSE = $VERBOSE, nil
       tmpdir = @tmpdir
       Dir.chdir(tmpdir) do
         ENV["XDG_CONFIG_HOME"] = "#{tmpdir}/xdg"
-        IRB.conf[:RC_NAME_GENERATOR] = nil
-        assert_equal(tmpdir+"/.irbrc", IRB.rc_file)
-        assert_equal(tmpdir+"/.irb_history", IRB.rc_file("_history"))
+        reset_rc_name_generators
+        assert_empty(IRB.irbrc_files)
+        assert_equal("#{ENV["HOME"]}/.irb_history", IRB.rc_file("_history"))
```
Comment (st0012) [inline test/irb/test_init.rb:48]: Isn't this the same as `tmpdir`? I understand that it's to emphasise that this value should be home, but I feel it could be misleading if we use `ENV["HOME"]` and `tmpdir` for the same value.

File: test/irb/test_init.rb [hunk 2]
```diff
@@ -35,132 +40,82 @@ def test_setup_with_minimum_argv_does_not_change_dollar0
...
-      FileUtils.mkdir_p("#{tmpdir}/irb.rc")
-      FileUtils.mkdir_p("#{tmpdir}/$irbrc")
-
-      Dir.chdir(tmpdir) do
-        IRB.conf[:RC_NAME_GENERATOR] = nil
-        assert_includes IRB.rc_files, tmpdir+"/.irbrc"
-        assert_includes IRB.rc_files, tmpdir+"/_irbrc"
-        assert_includes IRB.rc_files, tmpdir+"/irb.rc"
-        assert_includes IRB.rc_files, tmpdir+"/$irbrc"
+        ENV['HOME'] = tmpdir
```
Comment (st0012) [inline test/irb/test_init.rb:106]: This is unnecessary because it's already done in `setup`.
```suggestion
```

File: test/irb/test_init.rb [hunk 3]
```diff
@@ -35,132 +40,82 @@ def test_setup_with_minimum_argv_does_not_change_dollar0
...
+        ENV['XDG_CONFIG_HOME'] = "#{ENV['HOME']}/.config"
+        FileUtils.mkdir_p(ENV['HOME'])
```
Comment (st0012) [inline test/irb/test_init.rb:108]: I think it's not needed because `@tmpdir` is already present?

```suggestion
```

File: lib/irb/init.rb [hunk 4]
```diff
@@ -395,42 +395,54 @@ def IRB.parse_opts(argv: ::ARGV)
...
-  def IRB.rc_file(ext = IRBRC_EXT)
-    warn "rc_file is deprecated, please use rc_files instead."
-    rc_files(ext).first
-  end
 
-  def IRB.rc_files(ext = IRBRC_EXT)
-    if !@CONF[:RC_NAME_GENERATOR]
-      @CONF[:RC_NAME_GENERATOR] ||= []
-      existing_rc_file_generators = []
+  def IRB.prepare_rc_name_generators
```
Comment (st0012) [inline lib/irb/init.rb:408]: Maybe we can declare this as private?
Also, I feel `prepare_irbrc_name_generators` is a clearer name.

File: lib/irb/init.rb [hunk 5]
```diff
@@ -446,13 +458,16 @@ def IRB.rc_file_generators
...
       yield proc{|rc| home+"/.irb#{rc}"}
-      yield proc{|rc| home+"/.config/irb/irb#{rc}"}
+      if xdg_config_home.nil? || xdg_config_home.empty?
+        yield proc{|rc| home+"/.config/irb/irb#{rc}"}
+      end
     end
+  end
+
+  # possible irbrc files in current directory
+  def IRB.generate_current_dir_irbrc_files
```
Comment (st0012) [inline lib/irb/init.rb:468]: Let's make this private too.

File: test/irb/test_init.rb (hunk 1 above)
Comment (tompng) [reply test/irb/test_init.rb:48]: I'll remove this `test_rc_file` because history file is tested more in another test `test_rc_files`

File: lib/irb/init.rb (hunk 5 above)
Comment (tompng) [reply lib/irb/init.rb]: Done.
Also changed rc_file_generators to private too

**Review by st0012 — APPROVED** [review]
Technically this is a breaking change as it removes `RC_NAME_GENERATOR` from `IRB.conf` entries. But from the [search](https://github.com/search?q=RC_NAME_GENERATOR&type=code&p=1) on GH, most (if not all) usages of it should have been using `ENV["IRBRC"]` instead. The number of its usages also looks small (maybe a few dozens?).
Therefore, I think we can bite the bullet and remove it to make things simpler.

**Comment by tompng** [comment]
I think `IRB.conf[: RC_NAME_GENERATOR]` is already changed from Proc to Array and released as v1.12.0
