### PR TITLE
Fix code terminated check with heredoc and backtick

### LINKED ISSUE #361: IRB can't recognize heredoc after words
## Description

It's same with [issues 18738 on bugs.ruby-lang](https://bugs.ruby-lang.org/issues/18738).

See the code below please.

```ruby
a, b = <<EOF, %w[ hello
thank you
ruby devs
EOF
world
]
p a
p b
```

This works well if you save it to a file, and run with ruby xxx.rb. The results are here:
```
"thank you\nruby devs\n"
["hello", "world"]
```

But when you type it to irb，the code will not end, and you will get:
```ruby
❯ irb
irb(main):001:0] a, b = <<EOF, %w[ hello
irb(main):002:0] thank you
irb(main):003:0] ruby devs
irb(main):004:0] EOF
irb(main):005:0] world
irb(main):006:0" ]
irb(main):007:-" 
irb(main):008:0" 
irb(main):009:0" 
irb(main):010:0" 
```

I found this issue when I read the mruby source code. in mruby, the token after the first line's hello should be `tHD_LITERAL_DELIM`. But in CRuby, there's no this token. I tried to dump CRuby's parser state, find that just after reading `<<EOF`，it will directly recognize the whole token `thank you\nruby\devs`. So, I think this may not be the bug of Ripper, but how IRB called Ripper using its `ruby-lex` line by line.

For your convenience, you can see the parser state.

```
Stack now 0 2 82 341
Entering state 580
Next token is token "string literal" (1.7-1.12: )
Shifting token "string literal" (1.7-1.12: )
Entering state 60
Reducing stack by rule 613 (line 4830):
-> $$ = nterm string_contents (1.12-1.12: )
Stack now 0 2 82 341 580 60
Entering state 301
Reading a token: Next token is token "literal content" (1.12-1.12: "thank you\nruby devs\n")
Shifting token "literal content" (1.12-1.12: "thank you\nruby devs\n")
Entering state 507
Reducing stack by rule 619 (line 4926):
   $1 = token "literal content" (1.12-1.12: "thank you\nruby devs\n")
-> $$ = nterm string_content (1.12-1.12: )
Stack now 0 2 82 341 580 60 301
Entering state 511
Reducing stack by rule 614 (line 4840):
   $1 = nterm string_contents (1.12-1.12: )
   $2 = nterm string_content (1.12-1.12: )
-> $$ = nterm string_contents (1.12-1.12: )
Stack now 0 2 82 341 580 60
Entering state 301
Reading a token: 
lex_state: BEG -> END at line 7453
Next token is token "terminator" (1.12-1.12: )
Shifting token "terminator" (1.12-1.12: )
Entering state 512
Reducing stack by rule 596 (line 4693):
   $1 = token "string literal" (1.7-1.12: )
   $2 = nterm string_contents (1.12-1.12: )
   $3 = token "terminator" (1.12-1.12: )
-> $$ = nterm string1 (1.7-1.12: )
Stack now 0 2 82 341 580
Entering state 109
Reducing stack by rule 594 (line 4683):
   $1 = nterm string1 (1.7-1.12: )
-> $$ = nterm string (1.7-1.12: )
Stack now 0 2 82 341 580
Entering state 108
Reading a token: 
lex_state: END -> BEG|LABEL at line 9814
Next token is token ',' (1.12-1.13: )
```

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.1.1                            
IRB version: irb 1.4.1 (2021-12-25)            
InputMethod: ReidlineInputMethod with Reline 0.3.1
RUBY_PLATFORM: x86_64-linux                    
LANG env: en_US.UTF-8                          
East Asian Ambiguous Width: 1  
```

## Terminal Emulator

Konsole or Windows Terminal

## Setting Files

Not using `~/.irbrc` and `~/.inputrc`?

### PR DESCRIPTION
**Pull request by tompng**
Fixes #361 and also fixes similar problem with ``def `();end`` ``self.`('sleep 1')`` (#334)

### Heredoc
This code shows a sample of finding heredoc_beg corresponding to heredoc_end.
```ruby
<<A+<<B+%[#{<<C+<<D
#{<<E+<<F
#{<<G+<<H
G
H
}
E
F
}
A
B
C
D
}]
```
In line 1, there are heredocs(A,B,C,D). These heredocs will start from the next line. (pushed into `pending_heredoc`)
Heredoc will be closed in an order `A → B → C → D`, so it should be reversed and pushed to start_token when reached a new line.

### Backtick
```
irb(main):001:0` def `();end
irb(main):002:0` 
irb(main):003:0` self.`('sleep 1')
irb(main):004:0` 
# expect
irb(main):001:0> def `(); end
=> :`
irb(main):002:0> self.`('sleep 1')
=> ""
```

Checks if backtick is `` `command` `` or not.
```ruby
`sleep 1`         #<Ripper::Lexer::Elem: on_backtick@1:0 BEG token: "`">
self.`('sleep 1') #<Ripper::Lexer::Elem: on_backtick@1:5 ARG token: "`">
def `(arg); end   #<Ripper::Lexer::Elem: on_backtick@1:4 ENDFN token: "`">
```

### lexer.parse.sort_by(&:pos)
Test that I added failed in ruby 2.5.0 and 2.6.0 without the third commit.
Result of `Ripper::Lexer.new("<<A\nA\n").parse` (used in < 2.7.0) is not ordered by position.
```
[#<struct Ripper::Lexer::Elem pos=[1, 0], event=:on_heredoc_beg, tok="<<A", state=EXPR_BEG>,
 #<struct Ripper::Lexer::Elem pos=[2, 0], event=:on_heredoc_end, tok="A\n", state=EXPR_BEG>,
 #<struct Ripper::Lexer::Elem pos=[1, 3], event=:on_nl, tok="\n", state=EXPR_BEG>]
```

### CODE REVIEW

File: lib/irb/ruby-lex.rb [hunk 1]
```diff
@@ -729,18 +730,27 @@ def check_string_literal(tokens)
...
+        pending_heredocs.reverse_each do |t|
+          start_token << t
+          end_type << :on_heredoc_end
+        end
+        pending_heredocs = []
       end
       i += 1
     end
-    start_token.last.nil? ? nil : start_token.last
+    pending_heredocs.first || start_token.last
```
Comment (st0012) [inline lib/irb/ruby-lex.rb:753]: The tests seem to pass without `pending_heredocs.first ||`. Would you mind adding another test to cover this scenario?

Comment (tompng) [reply lib/irb/ruby-lex.rb:753]: I added these test cases.
```ruby
['<<A;<<B', "<<A;<<B\n", "%W[\#{<<A;<<B", "%W[\#{<<A;<<B\n"]`
```
`process_string_literal` of these code should all be `<<A`.
without `pending_heredocs.first ||`, it  will be
```ruby
[nil, '<<A', '%W[', '<<A']
```

**Comment by st0012** [comment]
@k0kubun would you mind giving it a look too? thx

File: lib/irb/ruby-lex.rb (hunk 1 above)
Comment (st0012) [reply lib/irb/ruby-lex.rb:753]: 👍 thx

**Review by k0kubun — APPROVED** [review]
Looks good to me. Thank you!
