### PR TITLE
Fix UTF-16 autocompletion

### LINKED ISSUE #52: A method what is named with an encoding what is different from `Encoding.default_external` causes crash
1. input `define_method "a".encode(Encoding::UTF_16) do end` and Enter on UTF-8 terminal env
1. press Tab
1. crash

### PR DESCRIPTION
**Pull request by alexanderadam**
fixes #52

**PS:** I'm looking for a new adventure in case anybody is looking to hire or work with a Ruby/Rails/Crystal dev

### CODE REVIEW

File: lib/irb/completion.rb [hunk 1]
```diff
@@ -453,16 +453,30 @@ def retrieve_completion_data(input, bind:, doc_namespace:)
...
       end
     end
 
     # Set of available operators in Ruby
     Operators = %w[% & * ** + - / < << <= <=> == === =~ > >= >> [] []= ^ ! != !~]
 
+    def safe_grep(candidates, pattern)
+      target_encoding = Encoding.default_external
+      candidates.filter_map do |candidate|
+        next unless candidate
```
Comment (tompng) [inline lib/irb/completion.rb]: I think this part is not needed because all candidate passed to `safe_grep` are converted to string with `.collect{|m| m.to_s}`

File: lib/irb/completion.rb [hunk 2]
```diff
@@ -453,16 +453,30 @@ def retrieve_completion_data(input, bind:, doc_namespace:)
...
+
+        converted = candidate.encoding == target_encoding ? candidate : candidate.encode(target_encoding)
```
Comment (tompng) [inline lib/irb/completion.rb]: Encoding conversion is more than safe-grep. I think this method should only do safe grep (`match?` and `rescue`) for simplicity.

Encoding conversion is already done in line 205.
```ruby
def completion_candidates(preposing, target, postposing, bind:)
  ...
  completion_data = retrieve_completion_data(target, bind: bind, doc_namespace: false).compact.filter_map do |i|
    i.encode(Encoding.default_external)
  rescue Encoding::UndefinedConversionError
    # If the string cannot be converted, we just ignore it
    nil
  end
  ...
end
```

File: lib/irb/completion.rb (hunk 1 above)
Comment (alexanderadam) [reply lib/irb/completion.rb]: I was surprised as well but without this  the tests fail on TruffleRuby (compare the builds on the two commits in this PR).

It's working on every other platform though. 🤔
Or was I missing a bit here or misunderstanding something?

/CC @eregon

File: lib/irb/completion.rb [hunk 3]
```diff
@@ -453,16 +453,30 @@ def retrieve_completion_data(input, bind:, doc_namespace:)
...
+
+        converted if pattern.match?(converted)
+      rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError, Encoding::CompatibilityError, EncodingError
```
[the remark this answers is not in the document]
Comment (alexanderadam) [reply lib/irb/completion.rb]: Ah, that absolutely makes sense! Thank you so much! :pray:
