### PR TITLE
Handle handle_exception's exception

### LINKED ISSUE #233: Ctrl+c can exit irb while in handle_exception phase of REPL.
## Description

if a very lengthy pretty-printing is being displayed, then during at least some portion of that time, Ctrl+c will cause irb to exit, losing all progress in whatever the user was doing, whereas the user would expect Ctrl+c to be trapped as usual.

## Result of irb_info

Ruby version: 3.0.1
IRB version: irb 1.3.5 (2021-04-03)
InputMethod: ReidlineInputMethod with Reline 0.2.5
RUBY_PLATFORM: x86_64-darwin20

## Terminal Emulator

MacOS Terminal.app

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

no

### PR DESCRIPTION
**Pull request by tompng**
Fix #233 and #779

Fix IRB crash when exception occurred inside handle_exception.

- Ctrl+C is pressed while printing exception
- Exception's encoding can't be converted
- Exception's method message, full_message, inspect raise error

### CODE REVIEW

File: lib/irb.rb [hunk 1]
```diff
@@ -744,6 +744,12 @@ def handle_exception(exc)
         puts message
       end
       print "Maybe IRB bug!\n" if irb_bug
+    rescue Exception
+      begin
+        print "#{exc.inspect}\n"
```
Comment (st0012) [inline lib/irb.rb:749]: I think we should hint users that something happened in the `handle_exception`, like:

```suggestion
    rescue Exception => handler_exc
      begin
        puts exc.inspect
        puts "backtraces are hidden because #{handler_exc} was raised when processing them"
```

Comment (tompng) [reply lib/irb.rb]: 👍  Updated

**Review by st0012 — APPROVED** [review]
